producer:
  build: ./producer
  volumes:
  - ./producer:/opt/app
  ports:
   - "8080:8080"
  links:
   - queue

consumer:
  build: ./consumer
  volumes:
   - ./consumer:/opt/app
  ports:
   - "8081:8080"
  links:
   - queue

consumercassandra:
  build: ./consumer_cassandra
  volumes:
   - ./consumer_cassandra:/opt/app
  ports:
   - "8082:8080"
  links:
   - queue
   - db

queue:
  image: dockerfile/rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"
db:
 image: spotify/cassandra
 ports:
  - "7199:7199"
  - "7000:7000"
  - "7001:7001"
  - "9160:9160"
  - "9042:9042"
  - "8012:8012"
  - "61621:61621"

